version: "3.8"

services:
  api:
    container_name: lifePilotBackend
    build: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "--", "/usr/local/bin/docker-entrypoint.sh"]
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS=redis://redis:6379
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - DATABASE_URL=postgres://${POSTGRES_USER:-lifePilotUser}:${POSTGRES_PASSWORD:-lifePilotDB_dev_password}@postgres:5432/${POSTGRES_DB:-lifePilotDB}

  redis:
    image: redis:7-alpine
    container_name: lifePilotRedis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16-alpine
    container_name: lifePilotPostgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-lifePilotUser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-lifePilotDB_dev_password}
      - POSTGRES_DB=${POSTGRES_DB:-lifePilotDB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lifePilotUser} -d ${POSTGRES_DB:-lifePilotDB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data:
  postgres_data:
